source "https://rubygems.org"

gem "middleman", "~>3.0.13"
gem "middleman-livereload"
gem "middleman-emblem", "~> 1.1.1"
gem 'bootstrap-sass', '~> 2.3.1.0', :require => false

group :development do
  gem 'capistrano', '2.12.0'
end