source "https://rubygems.org"

gem "middleman", "3.0.14"
gem 'json', '~> 1.7.7'
gem "middleman-livereload"
gem 'ember-source', '1.0.0.rc5'
gem 'handlebars-source', '1.0.0.rc4'
gem 'ember-data-source'
gem "middleman-emblem", "~> 1.1.1"
gem 'bootstrap-sass', '~> 2.3.1.0', :require => false
gem 'middleman-emberscript', '~> 1.0.0'

group :development do
  gem 'capistrano', '2.12.0'
end